//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSorage.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAG
    {
        public TAG()
        {
            this.TAGSETS = new HashSet<TAGSET>();
        }
    
        public int TagId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TAGSET> TAGSETS { get; set; }
    }
}
