//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaSorage.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGSET
    {
        public int TagSetId { get; set; }
        public int NodeId { get; set; }
        public int TagId { get; set; }
    
        public virtual NODE NODE { get; set; }
        public virtual TAG TAG { get; set; }
    }
}
