IF EXISTS (SELECT name FROM dbo.sysobjects WHERE id = object_id(N'USERS') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	DROP TABLE TAGSETS;
	DROP TABLE TAGS;
	DROP TABLE NODES;
	DROP TABLE USERS;
END